fix makalu init build error
cannot find path /home/xiest1/makalu/mw-qc/vendor/qcom/nonhlos/Molokai.LA.1.0/common/build/ufs/bin/asic/NON-HLOS/image, looks l(CR) the Nonhlos is FAT format.

ERROR: /home/xiest1/makalu/mw-qc/kernel_platform/vendor/qcom/opensource/audio-kernel/BUILD.bazel:61:13: in module_deps attribute of ddk_module_config rule //vendor/qcom/opensource/audio-kernel:canoe_consolidate_machine_dlkm_config: rule '//vendor/qcom/opensource/audio-kernel:canoe_consolidate_aw882xx_dlkm' does not exist. Since this rule was created by the macro 'define_canoe', the error might have been caused by the macro implementation
ERROR: /home/xiest1/makalu/mw-qc/kernel_platform/vendor/qcom/opensource/audio-kernel/BUILD.bazel:61:13: Analysis of target '//vendor/qcom/opensource/audio-kernel:canoe_consolidate_machine_dlkm_config' failed
Analyzing: 3 targets (109 packages loaded, 120064 targets configured)
[489 / 489] no actions running
Target //soc-repo:canoe_consolidate_dtc_dist up-to-date:
  bazel-bin/soc-repo/canoe_consolidate_dtc_dist
ERROR: Analysis of target '//soc-repo:canoe_consolidate_all_vendor_module_dist' failed; build aborted: Analysis failed
INFO: Elapsed time: 16.307s, Critical Path: 2.03s
INFO: 53 processes: 436 action cache hit, 9 internal, 44 linux-sandbox.

Change-Id: I45d225ab0187aa06b8e7989b8eba7aafe44c3305
(cherry picked from commit 14751f59ff30c32ceef0b85eb1962d709f8831f0)
Reviewed-on: https://gerrit.mot.com/3806002
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Obi-Wan Kenobi
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Reviewed-by: Qiuying Lin <linqy3@motorola.com>
Submit-Approved: Jira Key